// Angular Websites/crud-practice-angular/src/app/components/employee-table/employee-table.component.ts
import { Component, SimpleChange, SimpleChanges } from '@angular/core';
import { Employee } from '../../../../models/employee';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-employee-table',
  imports: [
    FormsModule
  ],
  templateUrl: './employee-table.component.html',
  styleUrl: './employee-table.component.css'
})
export class EmployeeTableComponent {
  // if type not defined the type is any
  employees: Employee[] = [];
  pageNumber: number = 1;
  pageSize : number = 2;
  totalPages: number = 0;
  totalCount: number = 0;
  searchText : string = "";
  updateEmployeeId: number = -1;
  isUpdating: boolean = false;
  pagesArray : any[] = [];
  createEmployeeFormData : Employee = new Employee();
  updateEmployeeFormData: Employee = new Employee();

  // works like useEffect with empty dependency array i.e useEffect(() => {} , []); works while initializing the variables(first render).
  async ngOnInit() {
    await this.fetchData();
  }

  async fetchData() {
    let url = `http://localhost:5248/api/Employee?PageNumber=${this.pageNumber}&PageSize=${this.pageSize}`;

    if(this.searchText !== ""){
      url = `http://localhost:5248/api/Employee?PageNumber=${this.pageNumber}&PageSize=${this.pageSize}&SearchText=${this.searchText}`;
    }
    const response = await fetch(url);

    if (response.ok) {
      let paginatedData = await response.json();
      this.employees = paginatedData;
      this.totalPages = Number(response.headers.get('X-Total-Pages'));
      this.totalCount = Number(response.headers.get('X-Total-Count'));
      this.pagesArray = [];
      for(let i = 1; i<= this.totalPages; i++){
        this.pagesArray.push(i);
      }
      // console.log(this.employees);
      // console.log(this.totalPages);
    }
  }

  //Update Employee

  async handleUpdate(flag: number , employee:Employee){
    if(flag == 0){
      this.isUpdating = true;
      this.updateEmployeeId = employee.id;
      this.updateEmployeeFormData.id =  employee.id;
      this.updateEmployeeFormData.name = employee.name;
      this.updateEmployeeFormData.salary = employee.salary;
      this.updateEmployeeFormData.email = employee.email;
    }
    else{
      const response = await fetch(`http://localhost:5248/api/Employee/${this.updateEmployeeId}` , {
        method : "PUT",
        headers : {
          "Content-Type" : "application/json", 
        },
        body : JSON.stringify(this.updateEmployeeFormData)
      });

      if(response.ok){
        this.updateEmployeeId = -1;
        this.isUpdating = false;
        this.updateEmployeeFormData = new Employee();
        await this.fetchData();
      }
    }
  }


  //Delete Employee
  async deleteEmployee(id: number){
    const response = await fetch(`http://localhost:5248/api/Employee/${id}` , {
      method : 'DELETE',
    });

    if(response.ok){
      if(((this.totalCount) - ((this.pageNumber-1)*this.pageSize)) == 1 && this.pageNumber>1){
        this.pageNumber = this.pageNumber-1;
      }
      this.fetchData();
    }
  }


  //  Create Employee
  async createEmployee(){
    const response = await fetch(`http://localhost:5248/api/Employee` , {
      method : 'POST',
      headers : {
        'Content-Type' : 'application/json',
      },
      body : JSON.stringify(this.createEmployeeFormData),
    })

    if(response.ok){
      this.fetchData();
      this.createEmployeeFormData.name = "";
      this.createEmployeeFormData.id = -1;
      this.createEmployeeFormData.email = "";
      this.createEmployeeFormData.salary = 0;
    }
  }

  handlePagination(page: number){
    this.pageNumber = page;
    console.log(this.pageNumber)
    this.fetchData();
  }
}



<div>
    <form action="" (submit)="createEmployee()">
        <div>
            <label for="name">
                Enter Name
            </label>
            <input type="text" name="name" id="name" [(ngModel)]="createEmployeeFormData.name">
        </div>
        <div>
            <label for="email">
                Enter Email
            </label>
            <input type="email" name="email" id="email" [(ngModel)]="createEmployeeFormData.email">
        </div>
        <div>
            <label for="">
                Enter Salary
            </label>
            <input type="number" name="salary" id="salary" [(ngModel)]="createEmployeeFormData.salary">
        </div>
        <div>
            <input type="submit" value="Add Employee">
        </div>
    </form>
</div>

<table>
    <tr>
        <th>Employee Id</th>
        <th>Employee Name</th>
        <th>Email Address</th>
        <th>Salary</th>
        <th>Actions</th>
    </tr>

    @for(employee of employees; track employee.id){
    @if(isUpdating == true && updateEmployeeId == employee.id){
    <tr>
        <td>{{employee.id}}</td>
        <td><input type="text" name="name" id="name" [(ngModel)]="updateEmployeeFormData.name"></td>
        <td><input type="email" name="email" id="email" [(ngModel)]="updateEmployeeFormData.email"></td>
        <td><input type="number" name="salary" id="salary" [(ngModel)]="updateEmployeeFormData.salary"></td>
        <td>
            <button (click)="handleUpdate(1 , employee)">Update</button>
            <button (click)="deleteEmployee(employee.id)">Delete</button>
        </td>
    </tr>
    }
    @else{
    <tr>
        <td>{{employee.id}}</td>
        <td>{{employee.name}}</td>
        <td>{{employee.email}}</td>
        <td>{{employee.salary}}</td>
        <td>
            <button (click)="handleUpdate(0 , employee)">Update</button>
            <button (click)="deleteEmployee(employee.id)">Delete</button>
        </td>
    </tr>
    }
    }
</table>

<div>
    @for(page of pagesArray; track page){
    <button (click)="handlePagination(page)">{{page}}</button>
    }
</div>

// React Websites/CRUD722025/src/components/EmployeeTable.jsx
import React, { useEffect, useState } from 'react'

const EmployeeTable = () => {

    const [employeeList, setEmployeeList] = useState([]);
    const [pageNumber, setPageNumber] = useState(1);
    const [pageSize, setPageSize] = useState(2);
    const [searchText, setSearchText] = useState(null);
    const [totalPages, setTotalPages] = useState(0);
    let pagesArr = [];
    for (let i = 1; i <= totalPages; i++) {
        pagesArr.push(i);
    }
    const [totalCount, setTotalCount] = useState(0);
    const [addEmployee , setAddEmployee] = useState({
        "name" : "",
        "email" : "",
        "salary" : 0, 
    })
    const [updateEmployeeId , setUpdateEmployeeId] = useState(-1);
    const [isUpdating , setIsUpdating] = useState(false);
    const [updateEmployeeData , setUpdateEmployeeData] = useState({
        "name" : "",
        "email" : "",
        "salary" : 0
    });

    useEffect(() => {
        loadData();
    }, [pageNumber]);

    console.log(totalPages);
    async function loadData() {
        let baseUrl = `http://localhost:5248/api/Employee?PageNumber=${pageNumber}&PageSize=${pageSize}`;

        if (searchText != null) {
            baseUrl = `http://localhost:5248/api/Employee?PageNumber=${pageNumber}&PageSize=${pageSize}&SearchText=${searchText}`;
        }

        const response = await fetch(baseUrl);

        if (response.ok) {
            let data = await response.json();
            setEmployeeList(data);
            setTotalCount(await response.headers.get('X-Total-Count'));
            setTotalPages(await response.headers.get('X-Total-Pages'));
        }
    }

    function handleAddEmployeeChanges(event){
        event.preventDefault();
        setAddEmployee({...addEmployee , [event.target.name] : event.target.value});
        console.log(addEmployee);
    }

    async function handleDelete(id){
        const response = await fetch(`http://localhost:5248/api/Employee/${id}` , {
            method : 'DELETE'
        });

        if(response.ok){
            loadData();
        }

        if((((totalCount) - ((pageNumber - 1) * pageSize)) == 1) && pageNumber > 1){
            setPageNumber(pageNumber - 1);
        }
    }

    async function handleUpdateChanges(event) {
        setUpdateEmployeeData({...updateEmployeeData , [event.target.name] : event.target.value})
    }

    async function handleUpdate(id) {
        const response = await fetch(`http://localhost:5248/api/Employee/${id}` , {
            method : 'PUT',
            headers : {
                'Content-Type' : 'application/json'
            },
            body : JSON.stringify(updateEmployeeData),
        });

        if(response.ok){
            await loadData();
            setIsUpdating(false);
            setUpdateEmployeeId(-1);
            setUpdateEmployeeData({
                "name" : "",
                "email" : "",
                "salary" : 0
            });
        }
    }

    async function handleAddEmployee(event){
        event.preventDefault();
        const response = await fetch(`http://localhost:5248/api/Employee` , {
            method : 'POST',
            headers : {
                'Content-Type' : 'application/json',
            },
            body : JSON.stringify(addEmployee),
        });

        if(response.ok){
            await loadData();
        }
    }

    return (
        <>
            <div><h1>Employee Details</h1></div>
            <div>
                <h3>Create Employee</h3>
                <form action="">
                    <input type="text" name="name" id="name" placeholder='Enter name....' value={addEmployee.name} onChange={handleAddEmployeeChanges} onClick={handleUpdateChanges}/>
                    <br />
                    <input type="email" name="email" id="email" placeholder='Enter email....' value={addEmployee.email} onChange={handleAddEmployeeChanges} onClick={handleUpdateChanges}/>
                    <br />
                    <input type="number" name="salary" id="salary" placeholder='Enter salary....' value={addEmployee.salary} onChange={handleAddEmployeeChanges} onClick={handleUpdateChanges}/>
                    <br />
                    <button onClick={handleAddEmployee}>Add Employee</button>
                </form>
            </div>
            <br />
            <div>
                <table>
                    <thead>
                        <tr>
                            <th>Employee Id</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Salary</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {
                            employeeList.map((employee) => {
                                let condition = employee.id == updateEmployeeId && isUpdating;
                                return (
                                    <tr>
                                        <td>{employee.id}</td>
                                        {condition ?<td><input type="text" value={updateEmployeeData.name} name='name' onChange={handleUpdateChanges}/></td> :<td>{employee.name}</td>}
                                        {condition ? <td><input type="email" value={updateEmployeeData.email} name='email' onChange={handleUpdateChanges}/></td> :<td>{employee.email}</td>}
                                        {condition ? <td><input type="number" value={updateEmployeeData.salary} name='salary' onChange={handleUpdateChanges}/></td> : <td>{employee.salary}</td>}
                                        <td>{condition?<button onClick={() => {
                                            handleUpdate(employee.id);
                                        }}>Update</button> :<button onClick={
                                            () => {
                                                setIsUpdating(true);
                                                setUpdateEmployeeId(employee.id);
                                                setUpdateEmployeeData({
                                                    "name" : employee.name,
                                                    "email" : employee.email,
                                                    "salary" : employee.salary,
                                                })
                                            }
                                        }>Update</button>}
                                        <button onClick={() => {
                                            handleDelete(employee.id)
                                        }}>Delete</button></td>
                                    </tr>
                                )
                            })
                        }
                    </tbody>
                </table>
            </div>
            <div>
                {
                    pagesArr.map((page) => {
                        return (
                            <button onClick={() => setPageNumber(page)}>{page}</button>
                        )
                    })
                }
            </div>
        </>
    )
}

export default EmployeeTable
