// Angular Websites/crud-practice-angular/src/app/components/employee-table/employee-table.component.ts
import { Component, SimpleChange, SimpleChanges } from '@angular/core';
import { Employee } from '../../../../models/employee';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-employee-table',
  imports: [
    FormsModule
  ],
  templateUrl: './employee-table.component.html',
  styleUrl: './employee-table.component.css'
})
export class EmployeeTableComponent {
  // if type not defined the type is any
  employees: Employee[] = [];
  pageNumber: number = 1;
  pageSize : number = 2;
  totalPages: number = 0;
  totalCount: number = 0;
  searchText : string = "";
  updateEmployeeId: number = -1;
  isUpdating: boolean = false;
  pagesArray : any[] = [];
  createEmployeeFormData : Employee = new Employee();

  // works like useEffect with empty dependency array i.e useEffect(() => {} , []); works while initializing the variables(first render).
  async ngOnInit() {
    await this.fetchData();
  }

  async fetchData() {
    let url = `http://localhost:5248/api/Employee?PageNumber=${this.pageNumber}&PageSize=${this.pageSize}`;

    if(this.searchText !== ""){
      url = `http://localhost:5248/api/Employee?PageNumber=${this.pageNumber}&PageSize=${this.pageSize}&SearchText=${this.searchText}`;
    }
    const response = await fetch(url);

    if (response.ok) {
      let paginatedData = await response.json();
      this.employees = paginatedData;
      this.totalPages = Number(response.headers.get('X-Total-Pages'));
      this.totalCount = Number(response.headers.get('X-Total-Count'));
      this.pagesArray = [];
      for(let i = 1; i<= this.totalPages; i++){
        this.pagesArray.push(i);
      }
      // console.log(this.employees);
      // console.log(this.totalPages);
    }
  }

  //Delete Employee
  async deleteEmployee(id: number){
    const response = await fetch(`http://localhost:5248/api/Employee/${id}` , {
      method : 'DELETE',
    });

    if(response.ok){
      if(((this.totalCount) - ((this.pageNumber-1)*this.pageSize)) == 1 && this.pageNumber>1){
        this.pageNumber = this.pageNumber-1;
      }
      this.fetchData();
    }
  }


  //  Create Employee
  async createEmployee(){
    const response = await fetch(`http://localhost:5248/api/Employee` , {
      method : 'POST',
      headers : {
        'Content-Type' : 'application/json',
      },
      body : JSON.stringify(this.createEmployeeFormData),
    })

    if(response.ok){
      this.fetchData();
      this.createEmployeeFormData.name = "";
      this.createEmployeeFormData.id = -1;
      this.createEmployeeFormData.email = "";
      this.createEmployeeFormData.salary = 0;
    }
  }

  handlePagination(page: number){
    this.pageNumber = page;
    console.log(this.pageNumber)
    this.fetchData();
  }
}




<div>
    <form action="" (submit)="createEmployee()">
    <div>
        <label for="name">
            Enter Name
        </label>
        <input type="text" name="name" id="name" [(ngModel)]="createEmployeeFormData.name">
    </div>
    <div>
        <label for="email">
            Enter Email
        </label>
        <input type="email" name="email" id="email" [(ngModel)]="createEmployeeFormData.email">
    </div>
    <div>
        <label for="">
            Enter Salary
        </label>
        <input type="number" name="salary" id="salary" [(ngModel)]="createEmployeeFormData.salary">
    </div>
    <div>
        <input type="submit" value="Add Employee">
    </div>
</form>
</div>

<table>
    <tr>
        <th>Employee Id</th>
        <th>Employee Name</th>
        <th>Email Address</th>
        <th>Salary</th>
        <th>Actions</th>
    </tr>

    @for(employee of employees; track employee.id){
        <tr>
            <td>{{employee.id}}</td>
            <td>{{employee.name}}</td>
            <td>{{employee.email}}</td>
            <td>{{employee.salary}}</td>
            <td>
                <button>Update</button>
                <button (click)="deleteEmployee(employee.id)">Delete</button>
            </td>
        </tr>
    }
</table>

<div>
     @for(page of pagesArray; track page){
        <button (click)="handlePagination(page)">{{page}}</button>
     }   
</div>

// React Websites/Practice/src/components/EmployeeTable.jsx
import React, { useEffect, useState } from "react";

const EmployeeTable = () => {
  const [employeeList, setEmployeeList] = useState([]);
  const [pageNumber, setPageNumber] = useState(1);
  const [totalPages, setTotalPages] = useState(0);
  const [PageSize, setPageSize] = useState(2);
  const [totalCount, setTotalCount] = useState(0);
  const [createStudentFormData, setCreateStudentFormData] = useState({
    name: "",
    email: "",
    department: "",
  });

  useEffect(() => {
    fetchData();
  }, []);

  async function fetchData() {
    try {
      const response = await fetch(
        "http://localhost:5152/api/Student?PageNumber=1&PageSize=2"
      );
      const paginatedData = await response.json();
      setEmployeeList(paginatedData);
      setTotalPages(response.headers.get("X-Total-Pages"));
      setTotalCount(response.headers.get("X-Total-Count"));
    } catch (error) {
      console.error("Error fetching data:", error);
    }
  }

  let paginationArray = [];
  for (let i = 1; i <= totalPages; i++) {
    paginationArray.push(i);
  }

  async function handleSubmit(e){
    e.preventDefault();
    const response = await fetch('http://localhost:5152/api/Student' , {
      method : 'POST',
      headers : {
        'Content-Type' : 'application/json'
      },
      body : JSON.stringify(createStudentFormData)
    })

    if(!response.ok){
      console.log(response.status);
    }

    await fetchData();
  }

  function handleChange(e){
    setCreateStudentFormData({...createStudentFormData, [e.target.name] : e.target.value})
  }

  async function deleteStudent(studentId) {
    const response = await fetch(`http://localhost:5152/api/Student/${studentId}` , {
      method : 'DELETE',
    })

    if(!response.ok){
      console.log(response.status);
    }

    fetchData();
  }

  return (
    <div>
      <div>
        <br />
        <form onSubmit={handleSubmit}>
          <div>
            <input
              type="text"
              name="name"
              id="studentName"
              placeholder="Name"
              onChange={handleChange}
            />
          </div>
          <div>
            <input type="email" name="email" id="studentEmail" placeholder="Email" onChange={handleChange} />
          </div>
          <div>
            <input
              type="text"
              name="department"
              id="studentDepartment"
              placeholder="Department"
              onChange={handleChange}
            />
          </div>
          <br />
          <input type="submit" value="Add Student" />
        </form>
        <br />
      </div>
      <hr />
      <br />
      <table>
        <thead>
          <tr>
            <th>Student Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Department</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {employeeList.map((employee) => (
            <tr key={employee.studentId}>
              <td>{employee.studentId}</td>
              <td>{employee.name}</td>
              <td>{employee.email}</td>
              <td>{employee.department}</td>
              <td>
                <button>Update</button> <button onClick={()=>{
                  deleteStudent(employee.studentId)
                }}>Delete</button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <div>
        {paginationArray.map((page) => {
          return <button>{page}</button>;
        })}
      </div>
    </div>
  );
};

export default EmployeeTable;
